### ISSUE TITLE
Убрать подземных слизней

### ISSUE THREAD

**Issue by NikitaDotIvanov64** [take-my-evolution/Minecraft#2]
Убрать блядскийх слизней если это возможно

**Comment by take-my-evolution** [comment]
\minecraft\server\config\quark.cfg
нужно будет посмотреть как они нвзываются и ваырубить в конфиге на сервере

**Comment by NikitaDotIvanov64** [comment]
Эммм ну таки давай) опять на половину законченный квест.

**Comment by NikitaDotIvanov64** [comment]
И судя по коментам в телеге ты это таки сделал. Ну так перенеси в тестируется.

**Comment by take-my-evolution** [comment]
Проверено, земляных слизней больше нет
