### ISSUE TITLE
Написать bat скрипт.

### ISSUE THREAD

**Issue by NikitaDotIvanov64** [take-my-evolution/Minecraft#7]
Скрипт должен запускать майн, в аргументы скрипта нужно передевать ник и коль-во оперативы.

**Comment by NikitaDotIvanov64** [comment]
@Unrealized какие то еще аргументы нужно передавать, перед запуском?

**Comment by take-my-evolution** [comment]
Скрипт написал.  Но нужно разобраться как работе авторизация на серве. И что будет если зайдут два человека с одинаковыми никами.

**Comment by NikitaDotIvanov64** [comment]
@Unrealized если написал то давай его мне, если быть точным то залей его в ветку develop. Там есть батник, замени на твой.
Почему в dev, потому что почитай документ, удачная модель ветвления гит, что я скинул в телегу

**Comment by take-my-evolution** [comment]
Добавлены скрипты для запуска и синхронизации

Создал 3 отдельных батника.
synch_all целиком синхронизирует клиент
synch mods синхронизирует только моды
start запускает клиент, при запуске даёт ввести количество выделяемой памяти и ник пользователя.
Выглядят они не красиво но возложенную на них функцию выполняют. Допиливать не планирую, в планах перейти на bash
